module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    // customForms: theme => ({
    //   dark: {
    //     input: {
    //       color: theme('colors.gray.100'),
    //     },
    //   },
    //   default: {
    //     select: {
    //       borderColor: theme('colors.red.600'),
    //       backgroundColor: theme('colors.red.600'),
    //       color: theme('colors.gray.100'),

    //       '&:focus': {
    //         boxShadow: `0 0 0 1px ${theme('colors.red.600')}`,
    //         borderColor: theme('colors.red.600'),
    //       },
    //     },
    //   },
    // }),
    extend: {
      fontSize: {
        xxs: '0.7rem',
      },
      boxShadow: {
        navCategory: '0 5px 4px 0 rgba(0,0,0,0.18)',
        'itemsSlider-shallow': '0 5px 10px rgba(0, 0, 0, 0.2)',
        itemsSlider: '0 5px 10px rgba(0, 0, 0, 0.4)',
        'itemsSlider-wide': '0 5px 15px rgba(0, 0, 0, 0.6)',
      },
      screens: {
        xs: '320px',
        xxl: '1440px',
      },
      fontFamily: {
        body: ['Lato'],
        cairo: ['Cairo'],
      },
      colors: {
        'main-color': '#b72b2b',
        'main-text': '#fff',
        'cadet-blue': '#5F9EA0',
        'body-light': '#fff',
        'body-text-light': '#252525',
        'body-dark': '#252525',
        'body-text-dark': '#fff',
        'first-nav-light': '#252525',
        'first-nav-text-light': '#fff',
        'first-nav-dark': '#b72b2b',
        'first-nav-text-dark': '#fff',
        'second-nav-light': '#b72b2b',
        'second-nav-text-light': '#fff',
        'second-nav-dark': '#252525',
        'second-nav-text-dark': '#fff',
        'nav-cat-light': '#f7f7fa',
        'nav-cat-text-light': '#252525',
        'nav-cat-dark': '#414141',
        'nav-cat-text-dark': '#fff',
        'btn-primary-light': '#b72b2b',
        'btn-secondary-light': '#fff',
        'btn-primary-dark': '#414141',
        'btn-secondary-dark': '#fff',
        'side-light': '#fff',
        'side-light-text': '#252525',
        'side-dark': '#252525',
        'side-dark-text': '#fff',
        teal: '#008080 ',
        'nav-gradient-from': '#eaaeae',
        'nav-gradient-to': '#9d0707',
        'buy-options-main': '#f64f59',
        aliceblue: '#F0F8FF',
        gold: '#d3a13b',
      },
      spacing: {
        '1p': '1px',
        '2p': '2px',
        '3p': '3px',
        '4p': '4px',
        '5p': '5px',
        '20p': '20px',
        '25p': '25px',
        '30p': '30px',
        '35p': '35px',
        n57p: '-57px',
        '54p': '54px',
      },
      inset: {
        '1/2': '50%',
        '33p': '33%',
        '36p': '36%',
        10: '10px',
        8: '8px',
        n2: '-2px',
        2: '2px',
        n1: '-1px',
        1: '1px',
        50: '50px',
        100: '100%',
        n25: '-25px',
        n42: '-42px',
      },
      translate: {
        'n1/2': '-50%',
      },
      minWidth: {
        700: '700px',
        135: '135px',
        '50p': '50%',
        '75p': '75%',
      },
      maxWidth: {
        default: '1560px',
      },
      minHeight: {
        243: '243px',
      },
      zIndex: {
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
      },
      animation: {
        fadeIn: 'fadeIn 200ms ease-in forwards ',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0%' },
          '100%': { opacity: '100%' },
        },
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/custom-forms')],
};
